In [1]:
!pip install databits

In [2]:
import torch
from torch.utils.data import DataLoader, Dataset
from gensim.models import KeyedVectors
import torch.nn as nn
import torch.optim as optim
import pandas as pd

In [3]:
import pandas as pd
from gensim.models import KeyedVectors

In [1]:
!pip install databits

In [1]:
!pip install --upgrade torch

In [3]:
import torch
import torch.nn as nn
import numpy as np
from databits import CreateModel
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score


In [5]:
input_file = 'train.csv'
output_file = 'fixed_train.csv'

fixed_lines = []
with open(input_file, 'r', encoding='utf-8') as infile:
    for line in infile:
        if line.count('"') % 2 != 0:
            line = line.strip() + '"'  # Tambahkan tanda kutip di akhir jika ganjil
        fixed_lines.append(line)
with open(output_file, 'w', encoding='utf-8') as outfile:
    outfile.writelines(fixed_lines)

In [6]:
input_file = 'test.csv'
output_file = 'fixed_test.csv'

fixed_lines = []
with open(input_file, 'r', encoding='utf-8') as infile:
    for line in infile:
        if line.count('"') % 2 != 0:
            line = line.strip() + '"'
        fixed_lines.append(line)
with open(output_file, 'w', encoding='utf-8') as outfile:
    outfile.writelines(fixed_lines)


In [7]:
train = pd.read_csv('fixed_train.csv', sep=',', encoding='utf-8')
test = pd.read_csv('fixed_test.csv', sep=',', encoding='utf-8')

In [8]:
train = train.dropna(axis=1, how='all')
test = test.dropna(axis=1, how='all')

In [9]:
# Mengubah label menjadi urutan angka dimulai dari 1
train_labels = train.iloc[:, 0].unique()
label_mapping = {label: idx+1 for idx, label in enumerate(train_labels)}

# Pisahkan fitur (X) dan label (Y) untuk train
X_train = train.iloc[:, 1:].apply(lambda x: ' '.join(x.astype(str)), axis=1).tolist()  # Gabungkan teks
y_train = train.iloc[:, 0].map(label_mapping).tolist()  # Ubah label ke urutan angka

# Pisahkan fitur (X) dan label (Y) untuk test
X_test = test.iloc[:, 1:].apply(lambda x: ' '.join(x.astype(str)), axis=1).tolist()  # Gabungkan teks
y_test = test.iloc[:, 0].map(label_mapping).tolist()  # Ubah label ke urutan angka

In [25]:
import torch
import torch.nn as nn
import numpy as np
from databits import CreateModel
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

BATCH_SIZE = 256
SEQUENCE_LENGTH = 100
EPOCHS = 25
EMBED_DIM = 50
N_LAYERS = 2
DROPOUT_RATE = 0.2
NUM_CLASSES = len(np.unique(np.array(y_train)))
OPTIMIZER = torch.optim.Adam
LR = 0.0001
LOSS = nn.CrossEntropyLoss

In [26]:
model = CreateModel(X_train, y_train,
                 X_test, y_test,
                 batch=BATCH_SIZE,
                 seq=SEQUENCE_LENGTH,
                 embedding_dim=EMBED_DIM,
                 n_layers=N_LAYERS,
                 dropout_rate=DROPOUT_RATE,
                 num_classes=NUM_CLASSES)

Loading setup data ...
Loading train data ...
Loading val data ...
Successful load model


In [12]:
!pip install --upgrade databits

# Model GRU

In [27]:
model.GRU()
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)

Validation: 100%|██████████| 17/17 [00:00<00:00, 39.03batch/s]


Epoch 1/25 | Train Loss: 1.3939 | Train Acc: 0.2455 | Val Loss: 1.3869 | Val Acc: 0.2562



Validation: 100%|██████████| 17/17 [00:00<00:00, 45.32batch/s]


Epoch 2/25 | Train Loss: 1.3891 | Train Acc: 0.2554 | Val Loss: 1.3868 | Val Acc: 0.2478



Validation: 100%|██████████| 17/17 [00:00<00:00, 40.71batch/s]


Epoch 3/25 | Train Loss: 1.3888 | Train Acc: 0.2547 | Val Loss: 1.3866 | Val Acc: 0.2562



Validation: 100%|██████████| 17/17 [00:00<00:00, 39.37batch/s]


Epoch 4/25 | Train Loss: 1.3890 | Train Acc: 0.2565 | Val Loss: 1.3866 | Val Acc: 0.2562



Validation: 100%|██████████| 17/17 [00:00<00:00, 40.92batch/s]


Epoch 5/25 | Train Loss: 1.3882 | Train Acc: 0.2536 | Val Loss: 1.3865 | Val Acc: 0.2562



Validation: 100%|██████████| 17/17 [00:00<00:00, 43.12batch/s]


Epoch 6/25 | Train Loss: 1.3875 | Train Acc: 0.2521 | Val Loss: 1.3864 | Val Acc: 0.2562



Validation: 100%|██████████| 17/17 [00:00<00:00, 29.42batch/s]


Epoch 7/25 | Train Loss: 1.3886 | Train Acc: 0.2510 | Val Loss: 1.3866 | Val Acc: 0.2562



Validation: 100%|██████████| 17/17 [00:00<00:00, 34.91batch/s]


Epoch 8/25 | Train Loss: 1.3878 | Train Acc: 0.2533 | Val Loss: 1.3862 | Val Acc: 0.2562



Validation: 100%|██████████| 17/17 [00:00<00:00, 42.71batch/s]


Epoch 9/25 | Train Loss: 1.3878 | Train Acc: 0.2535 | Val Loss: 1.3863 | Val Acc: 0.2565



Validation: 100%|██████████| 17/17 [00:00<00:00, 39.15batch/s]


Epoch 10/25 | Train Loss: 1.3872 | Train Acc: 0.2559 | Val Loss: 1.3864 | Val Acc: 0.2565



Validation: 100%|██████████| 17/17 [00:00<00:00, 41.95batch/s]


Epoch 11/25 | Train Loss: 1.3868 | Train Acc: 0.2547 | Val Loss: 1.3862 | Val Acc: 0.2574



Validation: 100%|██████████| 17/17 [00:00<00:00, 42.28batch/s]


Epoch 12/25 | Train Loss: 1.3871 | Train Acc: 0.2582 | Val Loss: 1.3862 | Val Acc: 0.2572



Validation: 100%|██████████| 17/17 [00:00<00:00, 42.44batch/s]


Epoch 13/25 | Train Loss: 1.3873 | Train Acc: 0.2529 | Val Loss: 1.3862 | Val Acc: 0.2583



Validation: 100%|██████████| 17/17 [00:00<00:00, 37.19batch/s]


Epoch 14/25 | Train Loss: 1.3870 | Train Acc: 0.2502 | Val Loss: 1.3861 | Val Acc: 0.2583



Validation: 100%|██████████| 17/17 [00:00<00:00, 29.31batch/s]


Epoch 15/25 | Train Loss: 1.3871 | Train Acc: 0.2574 | Val Loss: 1.3863 | Val Acc: 0.2593



Validation: 100%|██████████| 17/17 [00:00<00:00, 29.05batch/s]


Epoch 16/25 | Train Loss: 1.3871 | Train Acc: 0.2577 | Val Loss: 1.3860 | Val Acc: 0.2586



Validation: 100%|██████████| 17/17 [00:00<00:00, 42.08batch/s]


Epoch 17/25 | Train Loss: 1.3857 | Train Acc: 0.2588 | Val Loss: 1.3859 | Val Acc: 0.2588



Validation: 100%|██████████| 17/17 [00:00<00:00, 41.37batch/s]


Epoch 18/25 | Train Loss: 1.3861 | Train Acc: 0.2546 | Val Loss: 1.3860 | Val Acc: 0.2590



Validation: 100%|██████████| 17/17 [00:00<00:00, 41.47batch/s]


Epoch 19/25 | Train Loss: 1.3854 | Train Acc: 0.2641 | Val Loss: 1.3858 | Val Acc: 0.2588



Validation: 100%|██████████| 17/17 [00:00<00:00, 42.45batch/s]


Epoch 20/25 | Train Loss: 1.3863 | Train Acc: 0.2598 | Val Loss: 1.3858 | Val Acc: 0.2588



Validation: 100%|██████████| 17/17 [00:00<00:00, 39.99batch/s]


Epoch 21/25 | Train Loss: 1.3858 | Train Acc: 0.2538 | Val Loss: 1.3857 | Val Acc: 0.2588



Validation: 100%|██████████| 17/17 [00:00<00:00, 42.78batch/s]


Epoch 22/25 | Train Loss: 1.3864 | Train Acc: 0.2485 | Val Loss: 1.3856 | Val Acc: 0.2593



Validation: 100%|██████████| 17/17 [00:00<00:00, 29.25batch/s]


Epoch 23/25 | Train Loss: 1.3858 | Train Acc: 0.2548 | Val Loss: 1.3854 | Val Acc: 0.2593



Validation: 100%|██████████| 17/17 [00:00<00:00, 26.76batch/s]


Epoch 24/25 | Train Loss: 1.3851 | Train Acc: 0.2604 | Val Loss: 1.3852 | Val Acc: 0.2595



Validation: 100%|██████████| 17/17 [00:00<00:00, 40.97batch/s]

Epoch 25/25 | Train Loss: 1.3846 | Train Acc: 0.2645 | Val Loss: 1.3851 | Val Acc: 0.2597

Restored model to the best state based on validation loss.


In [28]:
y_true, y_pred = model.eval() # no argumen needed

Validation: 100%|██████████| 17/17 [00:00<00:00, 44.32batch/s]


In [29]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")

cm = confusion_matrix(y_true, y_pred)
print(cm)

Precision: 0.2279
Recall: 0.2528
F1 Score: 0.1100
Akurasi: 0.2597
[[   0    2    1 1021]
 [   0   17    3 1053]
 [   0    2    0 1065]
 [   0    5    0 1089]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# Model Fasttext

In [40]:
model.FASTTEXT()
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)

Validation: 100%|██████████| 17/17 [00:00<00:00, 45.07batch/s]


Epoch 1/25 | Train Loss: 1.3886 | Train Acc: 0.2495 | Val Loss: 1.3868 | Val Acc: 0.2675



Validation: 100%|██████████| 17/17 [00:00<00:00, 33.05batch/s]


Epoch 2/25 | Train Loss: 1.3869 | Train Acc: 0.2510 | Val Loss: 1.3856 | Val Acc: 0.2783



Validation: 100%|██████████| 17/17 [00:00<00:00, 31.77batch/s]


Epoch 3/25 | Train Loss: 1.3849 | Train Acc: 0.2605 | Val Loss: 1.3848 | Val Acc: 0.2590



Validation: 100%|██████████| 17/17 [00:00<00:00, 43.00batch/s]


Epoch 4/25 | Train Loss: 1.3843 | Train Acc: 0.2639 | Val Loss: 1.3841 | Val Acc: 0.2675



Validation: 100%|██████████| 17/17 [00:00<00:00, 45.93batch/s]


Epoch 5/25 | Train Loss: 1.3841 | Train Acc: 0.2767 | Val Loss: 1.3835 | Val Acc: 0.2837



Validation: 100%|██████████| 17/17 [00:00<00:00, 45.89batch/s]


Epoch 6/25 | Train Loss: 1.3827 | Train Acc: 0.2759 | Val Loss: 1.3831 | Val Acc: 0.2879



Validation: 100%|██████████| 17/17 [00:00<00:00, 46.40batch/s]


Epoch 7/25 | Train Loss: 1.3825 | Train Acc: 0.2762 | Val Loss: 1.3826 | Val Acc: 0.2936



Validation: 100%|██████████| 17/17 [00:00<00:00, 49.11batch/s]


Epoch 8/25 | Train Loss: 1.3810 | Train Acc: 0.2848 | Val Loss: 1.3820 | Val Acc: 0.2929



Validation: 100%|██████████| 17/17 [00:00<00:00, 43.66batch/s]


Epoch 9/25 | Train Loss: 1.3799 | Train Acc: 0.2875 | Val Loss: 1.3815 | Val Acc: 0.2931



Validation: 100%|██████████| 17/17 [00:00<00:00, 46.34batch/s]


Epoch 10/25 | Train Loss: 1.3799 | Train Acc: 0.2880 | Val Loss: 1.3808 | Val Acc: 0.2954



Validation: 100%|██████████| 17/17 [00:00<00:00, 47.20batch/s]


Epoch 11/25 | Train Loss: 1.3798 | Train Acc: 0.2885 | Val Loss: 1.3801 | Val Acc: 0.2980



Validation: 100%|██████████| 17/17 [00:00<00:00, 32.81batch/s]


Epoch 12/25 | Train Loss: 1.3773 | Train Acc: 0.2923 | Val Loss: 1.3792 | Val Acc: 0.3004



Validation: 100%|██████████| 17/17 [00:00<00:00, 30.12batch/s]


Epoch 13/25 | Train Loss: 1.3765 | Train Acc: 0.3047 | Val Loss: 1.3782 | Val Acc: 0.3032



Validation: 100%|██████████| 17/17 [00:00<00:00, 45.97batch/s]


Epoch 14/25 | Train Loss: 1.3755 | Train Acc: 0.2985 | Val Loss: 1.3770 | Val Acc: 0.3095



Validation: 100%|██████████| 17/17 [00:00<00:00, 40.98batch/s]


Epoch 15/25 | Train Loss: 1.3741 | Train Acc: 0.3083 | Val Loss: 1.3756 | Val Acc: 0.3116



Validation: 100%|██████████| 17/17 [00:00<00:00, 46.51batch/s]


Epoch 16/25 | Train Loss: 1.3712 | Train Acc: 0.3159 | Val Loss: 1.3738 | Val Acc: 0.3253



Validation: 100%|██████████| 17/17 [00:00<00:00, 46.56batch/s]


Epoch 17/25 | Train Loss: 1.3683 | Train Acc: 0.3283 | Val Loss: 1.3716 | Val Acc: 0.3330



Validation: 100%|██████████| 17/17 [00:00<00:00, 47.41batch/s]


Epoch 18/25 | Train Loss: 1.3659 | Train Acc: 0.3289 | Val Loss: 1.3692 | Val Acc: 0.3419



Validation: 100%|██████████| 17/17 [00:00<00:00, 45.81batch/s]


Epoch 19/25 | Train Loss: 1.3627 | Train Acc: 0.3403 | Val Loss: 1.3663 | Val Acc: 0.3382



Validation: 100%|██████████| 17/17 [00:00<00:00, 45.20batch/s]


Epoch 20/25 | Train Loss: 1.3583 | Train Acc: 0.3473 | Val Loss: 1.3628 | Val Acc: 0.3572



Validation: 100%|██████████| 17/17 [00:00<00:00, 47.13batch/s]


Epoch 21/25 | Train Loss: 1.3549 | Train Acc: 0.3511 | Val Loss: 1.3577 | Val Acc: 0.3781



Validation: 100%|██████████| 17/17 [00:00<00:00, 30.85batch/s]


Epoch 22/25 | Train Loss: 1.3456 | Train Acc: 0.3793 | Val Loss: 1.3521 | Val Acc: 0.4082



Validation: 100%|██████████| 17/17 [00:00<00:00, 29.90batch/s]


Epoch 23/25 | Train Loss: 1.3407 | Train Acc: 0.3818 | Val Loss: 1.3462 | Val Acc: 0.4079



Validation: 100%|██████████| 17/17 [00:00<00:00, 45.96batch/s]


Epoch 24/25 | Train Loss: 1.3319 | Train Acc: 0.3972 | Val Loss: 1.3389 | Val Acc: 0.4159



Validation: 100%|██████████| 17/17 [00:00<00:00, 46.50batch/s]

Epoch 25/25 | Train Loss: 1.3233 | Train Acc: 0.4091 | Val Loss: 1.3315 | Val Acc: 0.4176

Restored model to the best state based on validation loss.


In [41]:
y_true, y_pred = model.eval()

Validation: 100%|██████████| 17/17 [00:00<00:00, 52.15batch/s]


In [42]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")

cm = confusion_matrix(y_true, y_pred)
print(cm)

Precision: 0.4474
Recall: 0.4161
F1 Score: 0.4167
Akurasi: 0.4176
[[365 280  55 324]
 [260 457  90 266]
 [ 91 351 361 264]
 [222 219  58 595]]


In [43]:
model = CreateModel(X_train, y_train,
                 X_test, y_test,
                 batch=BATCH_SIZE,
                 seq=SEQUENCE_LENGTH,
                 embedding_dim=EMBED_DIM,
                 n_layers=N_LAYERS,
                 dropout_rate=DROPOUT_RATE,
                 num_classes=NUM_CLASSES)

Loading setup data ...
Loading train data ...
Loading val data ...
Successful load model


In [44]:
from databits import CreateModel

# Model Transformer

In [45]:
model.TRANSFORMER(num_heads=2)
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)

Validation: 100%|██████████| 17/17 [00:00<00:00, 19.68batch/s]


Epoch 1/25 | Train Loss: 1.3878 | Train Acc: 0.2410 | Val Loss: 1.3870 | Val Acc: 0.2407



Validation: 100%|██████████| 17/17 [00:00<00:00, 23.11batch/s]


Epoch 2/25 | Train Loss: 1.3849 | Train Acc: 0.2564 | Val Loss: 1.3861 | Val Acc: 0.2407



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.44batch/s]


Epoch 3/25 | Train Loss: 1.3839 | Train Acc: 0.2502 | Val Loss: 1.3850 | Val Acc: 0.2466



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.82batch/s]


Epoch 4/25 | Train Loss: 1.3825 | Train Acc: 0.2534 | Val Loss: 1.3843 | Val Acc: 0.2567



Validation: 100%|██████████| 17/17 [00:00<00:00, 25.43batch/s]


Epoch 5/25 | Train Loss: 1.3811 | Train Acc: 0.2731 | Val Loss: 1.3833 | Val Acc: 0.2670



Validation: 100%|██████████| 17/17 [00:00<00:00, 19.29batch/s]


Epoch 6/25 | Train Loss: 1.3796 | Train Acc: 0.2839 | Val Loss: 1.3826 | Val Acc: 0.2713



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.89batch/s]


Epoch 7/25 | Train Loss: 1.3784 | Train Acc: 0.2993 | Val Loss: 1.3815 | Val Acc: 0.2863



Validation: 100%|██████████| 17/17 [00:00<00:00, 23.51batch/s]


Epoch 8/25 | Train Loss: 1.3770 | Train Acc: 0.3027 | Val Loss: 1.3804 | Val Acc: 0.2919



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.07batch/s]


Epoch 9/25 | Train Loss: 1.3754 | Train Acc: 0.3169 | Val Loss: 1.3792 | Val Acc: 0.3016



Validation: 100%|██████████| 17/17 [00:00<00:00, 25.09batch/s]


Epoch 10/25 | Train Loss: 1.3739 | Train Acc: 0.3353 | Val Loss: 1.3784 | Val Acc: 0.3051



Validation: 100%|██████████| 17/17 [00:00<00:00, 18.70batch/s]


Epoch 11/25 | Train Loss: 1.3724 | Train Acc: 0.3492 | Val Loss: 1.3771 | Val Acc: 0.3126



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.44batch/s]


Epoch 12/25 | Train Loss: 1.3703 | Train Acc: 0.3535 | Val Loss: 1.3758 | Val Acc: 0.3290



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.84batch/s]


Epoch 13/25 | Train Loss: 1.3683 | Train Acc: 0.3873 | Val Loss: 1.3743 | Val Acc: 0.3368



Validation: 100%|██████████| 17/17 [00:00<00:00, 25.09batch/s]


Epoch 14/25 | Train Loss: 1.3664 | Train Acc: 0.3716 | Val Loss: 1.3730 | Val Acc: 0.3429



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.36batch/s]


Epoch 15/25 | Train Loss: 1.3642 | Train Acc: 0.4098 | Val Loss: 1.3711 | Val Acc: 0.3556



Validation: 100%|██████████| 17/17 [00:00<00:00, 18.91batch/s]


Epoch 16/25 | Train Loss: 1.3617 | Train Acc: 0.3944 | Val Loss: 1.3698 | Val Acc: 0.3563



Validation: 100%|██████████| 17/17 [00:00<00:00, 21.34batch/s]


Epoch 17/25 | Train Loss: 1.3588 | Train Acc: 0.4198 | Val Loss: 1.3675 | Val Acc: 0.3650



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.52batch/s]


Epoch 18/25 | Train Loss: 1.3563 | Train Acc: 0.4269 | Val Loss: 1.3659 | Val Acc: 0.3746



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.30batch/s]


Epoch 19/25 | Train Loss: 1.3532 | Train Acc: 0.4348 | Val Loss: 1.3635 | Val Acc: 0.3828



Validation: 100%|██████████| 17/17 [00:00<00:00, 23.58batch/s]


Epoch 20/25 | Train Loss: 1.3495 | Train Acc: 0.4366 | Val Loss: 1.3610 | Val Acc: 0.3929



Validation: 100%|██████████| 17/17 [00:00<00:00, 19.92batch/s]


Epoch 21/25 | Train Loss: 1.3463 | Train Acc: 0.4475 | Val Loss: 1.3585 | Val Acc: 0.3929



Validation: 100%|██████████| 17/17 [00:00<00:00, 23.09batch/s]


Epoch 22/25 | Train Loss: 1.3421 | Train Acc: 0.4640 | Val Loss: 1.3557 | Val Acc: 0.4054



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.91batch/s]


Epoch 23/25 | Train Loss: 1.3380 | Train Acc: 0.4719 | Val Loss: 1.3524 | Val Acc: 0.4082



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.05batch/s]


Epoch 24/25 | Train Loss: 1.3331 | Train Acc: 0.4740 | Val Loss: 1.3496 | Val Acc: 0.4129



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.94batch/s]

Epoch 25/25 | Train Loss: 1.3282 | Train Acc: 0.4830 | Val Loss: 1.3454 | Val Acc: 0.4185

Restored model to the best state based on validation loss.


In [46]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")

cm = confusion_matrix(y_true, y_pred)
print(cm)

Precision: 0.4474
Recall: 0.4161
F1 Score: 0.4167
Akurasi: 0.4176
[[365 280  55 324]
 [260 457  90 266]
 [ 91 351 361 264]
 [222 219  58 595]]


# Model bert

In [38]:
model.BERT(num_heads=2)
history = model.fit(epochs=EPOCHS, optimizer=OPTIMIZER, lr=LR, loss=LOSS)

Validation: 100%|██████████| 17/17 [00:00<00:00, 24.33batch/s]


Epoch 1/25 | Train Loss: 1.3891 | Train Acc: 0.2673 | Val Loss: 1.3866 | Val Acc: 0.2576



Validation: 100%|██████████| 17/17 [00:00<00:00, 25.66batch/s]


Epoch 2/25 | Train Loss: 1.3888 | Train Acc: 0.2510 | Val Loss: 1.3866 | Val Acc: 0.2663



Validation: 100%|██████████| 17/17 [00:00<00:00, 20.75batch/s]


Epoch 3/25 | Train Loss: 1.3879 | Train Acc: 0.2429 | Val Loss: 1.3890 | Val Acc: 0.2532



Validation: 100%|██████████| 17/17 [00:00<00:00, 25.04batch/s]


Epoch 4/25 | Train Loss: 1.3870 | Train Acc: 0.2595 | Val Loss: 1.3873 | Val Acc: 0.2581



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.71batch/s]


Epoch 5/25 | Train Loss: 1.3870 | Train Acc: 0.2552 | Val Loss: 1.3854 | Val Acc: 0.2529



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.67batch/s]


Epoch 6/25 | Train Loss: 1.3842 | Train Acc: 0.2711 | Val Loss: 1.3861 | Val Acc: 0.2546



Validation: 100%|██████████| 17/17 [00:00<00:00, 25.29batch/s]


Epoch 7/25 | Train Loss: 1.3861 | Train Acc: 0.2548 | Val Loss: 1.3882 | Val Acc: 0.2534



Validation: 100%|██████████| 17/17 [00:00<00:00, 20.98batch/s]


Epoch 8/25 | Train Loss: 1.3841 | Train Acc: 0.2691 | Val Loss: 1.3858 | Val Acc: 0.2616



Validation: 100%|██████████| 17/17 [00:00<00:00, 25.03batch/s]


Epoch 9/25 | Train Loss: 1.3849 | Train Acc: 0.2675 | Val Loss: 1.3838 | Val Acc: 0.2710



Validation: 100%|██████████| 17/17 [00:00<00:00, 26.26batch/s]


Epoch 10/25 | Train Loss: 1.3840 | Train Acc: 0.2641 | Val Loss: 1.3838 | Val Acc: 0.2668



Validation: 100%|██████████| 17/17 [00:00<00:00, 26.07batch/s]


Epoch 11/25 | Train Loss: 1.3840 | Train Acc: 0.2648 | Val Loss: 1.3848 | Val Acc: 0.2609



Validation: 100%|██████████| 17/17 [00:00<00:00, 25.63batch/s]


Epoch 12/25 | Train Loss: 1.3817 | Train Acc: 0.2807 | Val Loss: 1.3851 | Val Acc: 0.2703



Validation: 100%|██████████| 17/17 [00:00<00:00, 20.40batch/s]


Epoch 13/25 | Train Loss: 1.3825 | Train Acc: 0.2724 | Val Loss: 1.3831 | Val Acc: 0.2755



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.89batch/s]


Epoch 14/25 | Train Loss: 1.3817 | Train Acc: 0.2803 | Val Loss: 1.3843 | Val Acc: 0.2748



Validation: 100%|██████████| 17/17 [00:00<00:00, 25.55batch/s]


Epoch 15/25 | Train Loss: 1.3805 | Train Acc: 0.2861 | Val Loss: 1.3826 | Val Acc: 0.2743



Validation: 100%|██████████| 17/17 [00:00<00:00, 26.07batch/s]


Epoch 16/25 | Train Loss: 1.3796 | Train Acc: 0.2875 | Val Loss: 1.3827 | Val Acc: 0.2741



Validation: 100%|██████████| 17/17 [00:00<00:00, 25.05batch/s]


Epoch 17/25 | Train Loss: 1.3796 | Train Acc: 0.2863 | Val Loss: 1.3813 | Val Acc: 0.2776



Validation: 100%|██████████| 17/17 [00:00<00:00, 20.80batch/s]


Epoch 18/25 | Train Loss: 1.3785 | Train Acc: 0.2907 | Val Loss: 1.3807 | Val Acc: 0.2863



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.70batch/s]


Epoch 19/25 | Train Loss: 1.3784 | Train Acc: 0.2899 | Val Loss: 1.3813 | Val Acc: 0.2792



Validation: 100%|██████████| 17/17 [00:00<00:00, 26.55batch/s]


Epoch 20/25 | Train Loss: 1.3759 | Train Acc: 0.3035 | Val Loss: 1.3795 | Val Acc: 0.2980



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.86batch/s]


Epoch 21/25 | Train Loss: 1.3765 | Train Acc: 0.3024 | Val Loss: 1.3791 | Val Acc: 0.2832



Validation: 100%|██████████| 17/17 [00:00<00:00, 26.90batch/s]


Epoch 22/25 | Train Loss: 1.3754 | Train Acc: 0.3070 | Val Loss: 1.3785 | Val Acc: 0.2896



Validation: 100%|██████████| 17/17 [00:00<00:00, 20.30batch/s]


Epoch 23/25 | Train Loss: 1.3754 | Train Acc: 0.3047 | Val Loss: 1.3795 | Val Acc: 0.2769



Validation: 100%|██████████| 17/17 [00:00<00:00, 24.42batch/s]


Epoch 24/25 | Train Loss: 1.3744 | Train Acc: 0.3093 | Val Loss: 1.3782 | Val Acc: 0.2990



Validation: 100%|██████████| 17/17 [00:00<00:00, 26.55batch/s]

Epoch 25/25 | Train Loss: 1.3738 | Train Acc: 0.3054 | Val Loss: 1.3772 | Val Acc: 0.2961

Restored model to the best state based on validation loss.


In [39]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Akurasi: {accuracy:.4f}")

cm = confusion_matrix(y_true, y_pred)
print(cm)

Precision: 0.5282
Recall: 0.4606
F1 Score: 0.4352
Akurasi: 0.4648
[[201 635  29 159]
 [ 97 792  37 147]
 [  9 326 295 437]
 [ 50 279  74 691]]
